### ISSUE TITLE
更新角色权限的时候，系统异常

### ISSUE THREAD

**Issue by etherfurnace** [WeOps-Lab/weops_lite#4]
问题：
* 更新角色权限的时候，系统异常
* 系统异常的时候，没有返回异常的message

![image](https://github.com/WeOps-Lab/weops_lite/assets/81210463/ac3b8f9e-1381-442c-9fce-bcb555f4587c)

异常日志：

```
[2024-02-06 17:19:04,100][apps.process_exception():36] [ERROR] 捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/local/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/apps/./apps/core/decorators/uma_permission.py", line 23, in wrapper
    return wrapped(*args, **kwargs)
  File "/apps/./apps/system_mgmt/views/user_manage.py", line 405, in ch_permission
    UserManage().role_set_permissions(request, pk)
  File "/apps/./apps/system_mgmt/services/user_manage.py", line 481, in role_set_permissions
    supplement_api.update_permission(client_id, permission_info["id"], permission_info)
  File "/apps/./apps/system_mgmt/utils/keycloak.py", line 55, in update_permission
    return raise_error_from_response(data_raw, KeycloakGetError)
  File "/usr/local/lib/python3.10/site-packages/keycloak/exceptions.py", line 192, in raise_error_from_response
    raise error(
keycloak.exceptions.KeycloakGetError: 500: b'{"error":"unknown_error"}'
], 请求URL->[/api/role/数据库管理员/permissions/], 请求用户->[AnonymousUser] 请求方法->[PATCH] 请求参数->[null]

```

**Comment by baiyf-git** [comment]
问题已修复，commit为：870e583
附链接如下：
https://github.com/WeOps-Lab/weops_lite/commit/870e583e29f31e9a700e73b8b8e7e8bc3c3554d4
